### ISSUE TITLE
解析视频帧图片会花掉

### ISSUE THREAD

**Issue by zhaowenliang** [deepsadness/MediaMetadataRetrieverWrapper#1]
你在代码MainActivity中的两个列表适配器使用的是同一个数据源。修改后会发现解析视频帧会花掉。
```
mListView2 = (ListView) findViewById(R.id.list_view2);
//        mIvFrame = (ImageView) findViewById(R.id.iv_frame);
        mBitmapAdapter = new BitmapAdapter(bitmapArrayList);
        mListView2.setAdapter(mBitmapAdapter);

        mListView3 = (ListView) findViewById(R.id.list_view3);
//        mIvFrame = (ImageView) findViewById(R.id.iv_frame);
        mBitmapAdapter2 = new BitmapAdapter(bitmapArrayList);
        mListView3.setAdapter(mBitmapAdapter2);
```

**Comment by deepsadness** [comment]
> 你在代码MainActivity中的两个列表适配器使用的是同一个数据源。修改后会发现解析视频帧会花掉。
> 
> ```
> mListView2 = (ListView) findViewById(R.id.list_view2);
> //        mIvFrame = (ImageView) findViewById(R.id.iv_frame);
>         mBitmapAdapter = new BitmapAdapter(bitmapArrayList);
>         mListView2.setAdapter(mBitmapAdapter);
> 
>         mListView3 = (ListView) findViewById(R.id.list_view3);
> //        mIvFrame = (ImageView) findViewById(R.id.iv_frame);
>         mBitmapAdapter2 = new BitmapAdapter(bitmapArrayList);
>         mListView3.setAdapter(mBitmapAdapter2);
> ```

嗯。这里确实是写错了。不过改过来我这里是没问题的。你遇到什么问题了？可以把结果截图看一下。或者发一下源文件看看

**Comment by zhaowenliang** [comment]
图片怎么发给你，可以留个邮箱吗

**Comment by deepsadness** [comment]
这里可以直接发图片啊。拖到对话框就行

**Comment by zhaowenliang** [comment]
![Screenshot_2019-03-14-14-39-40-359_com example cry mediacodecimagereaderchain](https://user-images.githubusercontent.com/11538176/54337730-ba71ab00-466a-11e9-89f0-b1ee7189d39d.png)
![Screenshot_2019-03-14-14-38-33-308_com example cry mediacodecimagereaderchain](https://user-images.githubusercontent.com/11538176/54337731-ba71ab00-466a-11e9-9221-c27f6862444e.png)
是我太无知了。。。😰

**Comment by deepsadness** [comment]
嗯嗯。视频源文件方便传一下吗？我下载下来试试

**Comment by zhaowenliang** [comment]
视频太大，超过10MB了，传不上去。

**Comment by deepsadness** [comment]
加下QQ好了。295756092

**Comment by zhaowenliang** [comment]
目前出现问题的只有小米5S手机，其他手机没有发现问题。感谢大佬的帮助。
